on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/FUNDING.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/workflow_build.yaml
